version: 2

references:
  npm_cache_key: &npm_cache_key
    v2-dependency-npm-{{ checksum "package.json" }}
  npm_backup_cache_key: &npm_backup_cache_key
    v2-dependency-npm
  restore_node_modules: &restore_node_modules
    restore_cache:
      keys:
        - *npm_cache_key
        - *npm_backup_cache_key

aliases:
  - &use_docker_node8
    docker:
      - image: circleci/node:8
    working_directory: /tmp/project
  - &step_install
    steps:
      - checkout
      - *restore_node_modules
      - run:
          name: Install node dependencies
          command: yarn
      - save_cache:
          key: *npm_cache_key
          paths:
            - /tmp/project/node_modules
  - &step_test
    steps:
      - checkout
      - *restore_node_modules
      - run:
          name: Run tests
          command: |
            yarn test:standard
            yarn test:server
            yarn test:applications
  - &step_webpack
    steps:
      - checkout
      - *restore_node_modules
      - run:
          name: Build applications bundless
          command: |
            yarn build:applications
  - &step_build_docker_image
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build docker image
          command: docker build -t gperreymond/vue-nova-cms .

jobs:
  install:
    <<: *use_docker_node8
    <<: *step_install
  test:
    <<: *use_docker_node8
    <<: *step_test
  webpack:
    <<: *use_docker_node8
    <<: *step_webpack
  build_docker_image:
    <<: *use_docker_node8
    <<: *step_build_docker_image

workflows:
  version: 2
  commit-tests:
    jobs:
      - install:
          filters:
            branches:
              ignore: master
      - test:
          requires:
            - install
          filters:
            branches:
              ignore: master
  deploy-demo:
    jobs:
      - install:
          filters:
            branches:
              only: master
      - test:
          requires:
            - install
          filters:
            branches:
              only: master
      - webpack:
          requires:
            - test
          filters:
            branches:
              only: master
      - build_docker_image:
          requires:
            - webpack
          filters:
            branches:
              only: master
